include:
  - project: "dev/commun/templates"
    ref: 'v3'
    file: 
      - "templates/docker-push.yml"
      - "templates/docker-build.yml"
      - "templates/trivy-scan-image.yml"

stages:
  - docker-build-save
  - trivy-scan-image
  - docker-build-push

# ---

docker-build-save:
  extends: .docker-build-save
  stage: docker-build-save
  variables:
    CONTAINER_REGISTRY_URL: neufhs-docker-stages.${REPOSITOI_LOCAL_ZONE_HOSTNAME}
    IMAGE_NAME: gitlab-mr-conform
    IMAGE_TAG: 0.5.3
    IMAGE_TARBALL_NAME: gitlab-mr-conform
    DOCKER_COMPLEMENTARY_OPTIONS: >-
      --build-arg REPOSITOI_LOCAL_ZONE_HOSTNAME=${REPOSITOI_LOCAL_ZONE_HOSTNAME}
      --build-arg PLACIDE_STAGES_DOCKER_REPO=${PLACIDE_STAGES_DOCKER_REPO}
    ARTIFACTS_EXPIRE_IN: "5 mins"

trivy-scan-image:
  stage: trivy-scan-image
  extends: 
    - .trivy-scan-image
  variables:
    TRIVY_VIOLATIONS_SEVERITY_LEVEL: "HIGH"
    TRIVY_OPTIONS: "--severity HIGH,CRITICAL --show-suppressed"
    IMAGE_TAG: 0.5.3
    IMAGE_TARBALL_NAME: gitlab-mr-conform

docker-build-push:
  extends: .docker-build-push
  stage: docker-build-push
  variables:
    CONTAINER_REGISTRY_URL: neufhs-docker-stages.repositoi.zca.enedis.fr
    IMAGE_NAME: gitlab-mr-conform
    IMAGE_TAG: 0.5.3
    USE_BUILDKIT_CACHE: 'true'
    DOCKER_COMPLEMENTARY_OPTIONS: >-
      --build-arg REPOSITOI_LOCAL_ZONE_HOSTNAME=${REPOSITOI_ZCA_HOSTNAME}
      --build-arg PLACIDE_STAGES_DOCKER_REPO=${PLACIDE_STAGES_DOCKER_REPO}
