server:
  port: 8080
  host: "0.0.0.0"
  log_level: info

gitlab:
  # Set via environment variables:
  # GITLAB_MR_BOT_GITLAB_TOKEN
  # GITLAB_MR_BOT_GITLAB_SECRET_TOKEN
  base_url: "https://gitlab.com"

queue:
  enabled: false
  redis:
    host: "<your-redis-or-valkey-host>:6379"
    # Set using GITLAB_MR_BOT_QUEUE_REDIS_PASSWORD variable
    password: "redispassword"
    db: "0"
  queue:
    processing_interval: 100ms
    max_retries: 3
    lock_ttl: 10s

rules:
  title:
    enabled: false
    min_length: 10
    max_length: 100
    conventional:
      types:
        - "feat"
        - "fix"
        - "docs"
        - "refactor"
        - "release"
      scopes:
        - ".*"
    forbidden_words:
      - "WIP"
      - "TODO"
      - "FIXME"
    jira:
      keys:
        - PROJ
        - JIRA

  description:
    enabled: false
    required: true
    min_length: 20
    require_template: false

  branch:
    enabled: false
    allowed_prefixes: ["feature/", "bugfix/", "hotfix/", "release/"]
    forbidden_names: ["master", "main", "develop", "staging"]

  commits:
    enabled: false
    max_length: 72
    conventional:
      types:
        - "feat"
        - "fix"
        - "docs"
        - "refactor"
        - "release"
      scopes:
        - ".*"
    jira:
      keys: []

  approvals:
    enabled: true
    use_codeowners: false
    min_count: 1 # skipped if use_codeowners set to true

  squash:
    enabled: false
    enforce_branches:
      - "feature/*"
      - "fix/*"
    disallow_branches: ["release/*", "hotfix/*"]
