{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-mr-conform.secretName" . }}
  labels:
    {{- include "gitlab-mr-conform.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secret.data.gitlabToken }}
  gitlab-token: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.data.webhookSecret }}
  webhook-secret: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.data.redisPassword }}
  redis-password: {{ . | quote }}
  {{- end }}
{{- end }}