apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-mr-bot
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitlab-mr-bot
  template:
    metadata:
      labels:
        app: gitlab-mr-bot
    spec:
      containers:
      - name: bot
        image: gitlab-mr-conformity-bot:latest
        ports:
        - containerPort: 8080
        env:
        - name: GITLAB_BOT_GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitlab-bot-secrets
              key: gitlab-token
        - name: GITLAB_BOT_GITLAB_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitlab-bot-secrets
              key: webhook-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-mr-bot-service
spec:
  selector:
    app: gitlab-mr-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-bot-secrets
type: Opaque
data:
  gitlab-token: # base64 encoded GitLab token
  webhook-secret: # base64 encoded webhook secret