# Default values for gitlab-mr-bot
replicaCount: 2

image:
  repository: ghcr.io/chrxmvtik/gitlab-mr-conform
  tag: main
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: gitlab-mr-bot.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

nodeSelector: {}

tolerations: []

affinity: {}

# Secret configuration
secret:
  # Set to false if you want to use an existing secret
  create: true
  # Name of the secret (if create is false, this should be the existing secret name)
  name: ""
  # Secret data (base64 encoded values)
  data:
    gitlabToken: ""  # base64 encoded GitLab token
    webhookSecret: ""  # base64 encoded webhook secret

# Pod Security Context
podSecurityContext: {}

# Container Security Context
securityContext: {}

# Service Account
serviceAccount:
  create: false
  annotations: {}
  name: ""

# Pod annotations
podAnnotations: {}

# Pod labels
podLabels: {}

# Application configuration
config:
  # Set to false if you want to use an existing configmap
  create: true
  # Name of the configmap (if create is false, this should be the existing configmap name)
  name: ""
  # Configuration data
  data:
    server:
      port: 8080
      host: "0.0.0.0"
    gitlab:
      # Note: GITLAB_MR_BOT_GITLAB_TOKEN and GITLAB_MR_BOT_GITLAB_SECRET_TOKEN
      # are set via environment variables from the secret
      base_url: "https://gitlab.com"
    rules:
      title:
        enabled: true
        min_length: 10
        max_length: 100
        conventional:
          types:
            - "feat"
            - "fix"
            - "docs"
            - "refactor"
            - "release"
          scopes:
            - ".*"
        forbidden_words:
          - "WIP"
          - "TODO"
          - "FIXME"
        jira:
          keys:
            - "PROJ"
            - "JIRA"
      description:
        enabled: true
        required: true
        min_length: 20
        require_template: false
      branch:
        enabled: true
        allowed_prefixes:
          - "feature/"
          - "bugfix/"
          - "hotfix/"
          - "release/"
        forbidden_names:
          - "master"
          - "main"
          - "develop"
          - "staging"
      commits:
        enabled: true
        max_length: 72
        conventional:
          types:
            - "feat"
            - "fix"
            - "docs"
            - "refactor"
            - "release"
          scopes:
            - ".*"
        jira:
          keys: []
      approvals:
        enabled: false
        required: false
        min_count: 1
      squash:
        enabled: true
        enforce_branches:
          - "feature/*"
          - "fix/*"
        disallow_branches:
          - "release/*"
          - "hotfix/*"